const Post = require('../models/Post');
const User = require('../models/User'); 
const Review = require('../models/Review');

// @desc    Get all posts for the home feed
// @route   GET /api/posts
// @access  Public (for now)
const getFeedPosts = async (req, res) => {
  try {
    const posts = await Post.find()
      .populate('author', 'username profilePicture')
      .sort({ createdAt: -1 });

    res.status(200).json(posts);
  } catch (error) {
    res.status(500).json({ message: 'Failed to fetch posts', error: error.message });
  }
};

const createPost = async (req, res) => {
  try {
    const { caption, category, authorRating } = req.body;

    // Check if an image was uploaded
    if (!req.file) {
      return res.status(400).json({ message: 'An image is required' });
    }

    // req.user is set by our auth middleware
    // req.file.path is the secure Cloudinary URL generated by multer-storage-cloudinary
    const newPost = await Post.create({
      author: req.user._id,
      imageUrl: req.file.path, 
      caption,
      category,
      authorRating: Number(authorRating), // Ensure this is stored as a number
      communityAverageRating: 0,
      totalReviews: 0
    });

    // Populate the author data before sending it back so the frontend can render it immediately
    const populatedPost = await Post.findById(newPost._id).populate('author', 'username profilePicture');

    res.status(201).json(populatedPost);
  } catch (error) {
    console.error('Error creating post:', error);
    res.status(500).json({ message: 'Failed to create post', error: error.message });
  }
};

const getPostById = async (req, res) => {
  try {
    const post = await Post.findById(req.params.id).populate('author', 'username profilePicture');
    
    if (!post) {
      return res.status(404).json({ message: 'Post not found' });
    }

    // Fetch all reviews for this post and populate the user who wrote them
    const reviews = await Review.find({ post: post._id })
      .populate('user', 'username profilePicture')
      .sort({ createdAt: -1 }); // Newest reviews first

    res.status(200).json({ post, reviews });
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

// @desc    Add a review to a post
// @route   POST /api/posts/:id/reviews
// @access  Private
const addReview = async (req, res) => {
  try {
    const { rating, comment } = req.body;
    const postId = req.params.id;

    const post = await Post.findById(postId);
    if (!post) {
      return res.status(404).json({ message: 'Post not found' });
    }

    // Check if the user already reviewed this post
    const alreadyReviewed = await Review.findOne({
      post: postId,
      user: req.user._id,
    });

    if (alreadyReviewed) {
      return res.status(400).json({ message: 'You already reviewed this moment' });
    }

    // Create the new review
    const review = await Review.create({
      post: postId,
      user: req.user._id,
      rating: Number(rating),
      comment,
    });

    // Recalculate the community average rating
    const allReviews = await Review.find({ post: postId });
    post.totalReviews = allReviews.length;
    
    const totalRatingScore = allReviews.reduce((acc, item) => item.rating + acc, 0);
    post.communityAverageRating = totalRatingScore / allReviews.length;

    await post.save();

    // Send back the newly created review populated with the user data
    const populatedReview = await Review.findById(review._id).populate('user', 'username profilePicture');

    res.status(201).json(populatedReview);
  } catch (error) {
    res.status(500).json({ message: 'Failed to add review', error: error.message });
  }
};

const deletePost = async (req, res) => {
  try {
    const post = await Post.findById(req.params.id);

    if (!post) {
      return res.status(404).json({ message: 'Post not found' });
    }

    // Check for user authorization (ensure the logged-in user owns the post)
    if (post.author.toString() !== req.user.id) {
      return res.status(401).json({ message: 'User not authorized to delete this post' });
    }

    // Optional: You could also add logic here to delete the image from Cloudinary using their API

    // Delete all reviews associated with this post
    await Review.deleteMany({ post: req.params.id });

    // Delete the post itself
    await post.deleteOne();

    res.status(200).json({ id: req.params.id, message: 'Post deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: 'Failed to delete post', error: error.message });
  }
};

const toggleLike = async (req, res) => {
  try {
    const post = await Post.findById(req.params.id);

    if (!post) {
      return res.status(404).json({ message: 'Post not found' });
    }

    // Check if the post has already been liked by this user
    const isLiked = post.likes.includes(req.user.id);

    if (isLiked) {
      // If liked, remove the user ID from the array
      post.likes = post.likes.filter((userId) => userId.toString() !== req.user.id);
    } else {
      // If not liked, add the user ID to the array
      post.likes.push(req.user.id);
    }

    await post.save();

    // Return the updated likes array
    res.status(200).json(post.likes);
  } catch (error) {
    res.status(500).json({ message: 'Failed to toggle like', error: error.message });
  }
};



// Update your module.exports at the bottom:
module.exports = {
  getFeedPosts,
  createPost,
  getPostById,
  addReview,
  deletePost,
  toggleLike,
};